{
 "title": "FIWARE Smart Store",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Luminosity Map",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "rawSql": "SELECT time_index, entity_id, luminosity, location FROM etlamp WHERE $__timeFilter(time_index) ORDER BY time_index ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Motion Detection",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "rawSql": "SELECT time_index AS \"time\", count AS \".\", entity_id FROM etmotion WHERE $__timeFilter(time_index) ORDER BY time_index ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Luminosity Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "rawSql": "SELECT time_index AS \"time\", luminosity, entity_id FROM etlamp WHERE $__timeFilter(time_index) ORDER BY time_index ASC "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT entity_id, time_index, luminosity FROM etlamp ORDER BY time_index ASC "
    }
   ]
  }
 ]
}