{
 "title": "FIWARE Smart Store",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "Luminosity Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "rawSql": "SELECT time_index AS \"time\", luminosity, entity_id FROM etlamp WHERE $__timeFilter(time_index) ORDER BY time_index ASC "
    }
   ]
  },
  {
   "title": "Motion Detection",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "rawSql": "SELECT time_index AS \"time\", count AS \".\", entity_id FROM etmotion WHERE $__timeFilter(time_index) ORDER BY time_index ASC "
    }
   ]
  },
  {
   "title": "Door Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "rawSql": "SELECT entity_id, state AS \".\", time_index AS \"time\" FROM etdoor WHERE $__timeFilter(time_index) "
    }
   ]
  },
  {
   "title": "Luminosity Map",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "rawSql": "SELECT time_index, entity_id, location, luminosity FROM etlamp WHERE $__timeFilter(time_index) ORDER BY time_index ASC "
    }
   ]
  },
  {
   "title": "Panel Luminosity Gauges",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT entity_id, luminosity AS \".\", time_index AS \"time\" FROM etlamp WHERE $__timeFilter(time_index) ORDER BY time_index ASC "
    }
   ]
  },
  {
   "title": "panel Luminosity Bar Gauges",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT entity_id, luminosity AS \".\", time_index AS \"time\" FROM etlamp WHERE $__timeFilter(time_index) ORDER BY time_index ASC LIMIT null "
    }
   ]
  },
  {
   "title": "Panel Last Motion Detection",
   "type": "canvas",
   "description": "\n",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "rawSql": "SELECT entity_id, time_index AS \"time\", count AS \".\" FROM etmotion WHERE $__timeFilter(time_index) ORDER BY time_index ASC LIMIT null "
    }
   ]
  }
 ]
}